     layx = pnew_op.nlevs(ii)-1;
     semilogy(pnew_ip.ptemp(:,ii),pnew_ip.plevs(:,ii),'b+-',pnew_op.ptemp(1:layx,ii),pnew_op.plays(1:layx,ii),'rx-',...
                   pnew_ip.stemp(ii),pnew_ip.spres(ii),'go',pnew_ip.t2m(ii),pnew_ip.spres(ii),'ko',T2m_test(ii),pnew_ip.spres(ii),'co',...
                   pnew_op.stemp(ii),pnew_op.spres(ii),'g.',pnew_op.t2m(ii),pnew_op.spres(ii),'k.',T2m_test(ii),pnew_ip.spres(ii),'c.',...
                   pnew_op.ptemp(1:layx+1,ii),pnew_op.plays(1:layx+1,ii),'rx--',...
                   'linewidth',2)
